### ISSUE TITLE
allow package to be built for iOS9+, though not run on iOS9+

### ISSUE THREAD

**Issue by andrewljohnson** [ProjectDent/ARKit-CoreLocation#28]
Have you looked into making ARCL build for iOS9/10, so one could package it with an iOS9+ app, and conditionally reveal ARCL functionality only on iOS11? 

I was going to see what's involved in this, and wonder if you had looked at all.

**Comment by ProjectDent** [comment]
Fixed with #38

**Comment by NDBellisario** [comment]
Still getting pods telling me there a dependency issue any advice on how to fix this? 
I have mine set to iOS 10.0
Specs satisfying the `ARCL` dependency were found, but they required a higher minimum deployment target.

**Comment by vihanb** [comment]
@NDBellisario I don't believe the cocoapod has been updated yet so you may need to change your Podfile with:
```
pod 'ARCL', :git => 'https://github.com/ProjectDent/ARKit-CoreLocation.git', :commit => '8f73aeaebe2cc8ab489c0a2d1a77e6a67665438c'
```

**Comment by NDBellisario** [comment]
@vihanb Thank you that did it!
